#!/bin/bash
#
# Title:           socket-proxy
# Author:          ALPHA
# Dockerowner:     fluencelabs
# GNU:             General Public License v3.0

# Description:     Use socket_proxy network instead of directly exposing containers to docker-sock which can turn out to be dangerous 

# Creating socket_proxy docker network
- name: 'creating socket_proxy docker network'
  shell: "docker network create --gateway 192.168.91.1 --subnet 192.168.91.0/24 socket_proxy"
  register: socket_proxy
# Including Core Taks
- name: 'Including main job'
  include_tasks: '/opt/coreapps/apps/_core.yml'
################################################################################
---
- hosts: "127.0.0.1"
  gather_facts: false
  tasks:
    # FACTS
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'socket-proxy'
        intport: '2375'
        extport: '2375'
        image: 'fluencelabs/docker-socket-proxy'
    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'
          EVENTS: "1"
          PING: "1"
          VERSION: "1"
          AUTH: "0"
          SECRETS: "0"
          POST: "1"
          DELETE: "1"
          BUILD: "0"
          COMMIT: "0"
          CONFIGS: "0"
          CONTAINERS: "1"
          DISTRIBUTION: "0"
          EXEC: "0"
          IMAGES: "1"
          INFO: "1" 
          NETWORKS: "1"
          NODES: "0"
          PLUGINS: "0"
          SERVICES: "1" 
          SESSION: "0"
          SWARM: "0"
          SYSTEM: "0"
          TASKS: "1"
          VOLUMES: "1" 
          CONTAINERS_CREATE: "1"
          CONTAINERS_START: "1"
          CONTAINERS_UPDATE: "1"
          CONTAINERS_DELETE: "1"
          IMAGES_DELETE: "1"

     ########## DEPLOYMENT ##########
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        hostname: 'socket-proxy'
        pull: yes
        published_ports:
          - '{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        privileged: true
        restart_policy: always
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
          - name: socket_proxy
            ipv4_address: "192.168.91.254" # You can specify a static IP
        state: started
  
     
